---

- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
    
  tasks:
    - name: Backup Mysql / Mariadb databases from docker
      command: sh files/backup.sh

    - name: Make a cron to run every 3 hours
      cron:
        name: docker_database_backup
        minute: '0'
        hour: '*/3'
        job: 'ansible-playbook {{folder}}/backup.yml >/dev/null 2>&1'
        state: present

    - name: Make a cron to delete local database backups older than 2 days
      cron:
        name: Remove local database backups older than 2 days
        minute: '0'
        hour: '0'
        job: 'find {{backup}} -mtime -1 -delete >/dev/null 2>&1'

    - name: send completion alert Discord
      include_tasks: playbooks/send_comp_alert.yml
      tags: always
      when:
       - task_failed is not defined

    - name: send failure alert Discord
      include_tasks: playbooks/send_failure_alert.yml
      tags: always
      when:
       - task_failed is defined
       - task_failed == true
