- name: Send notify to Telegram
  community.general.telegram:
    token: {{telegram_token}}
    api_args:
      chat_id: {{telegram_chat_id}}
      parse_mode: "markdown"
      text: "⚠️  Docker Database Backup failed on *{{ansible_hostname}}*"
      disable_web_page_preview: false
      disable_notification: false
